# Generated by Django 4.2.7 on 2024-11-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='data_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
