# Generated by Django 4.2.7 on 2024-01-18 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_version_id_alter_version_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={},
        ),
    ]
