# Generated by Django 4.2.7 on 2024-02-04 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'verbose_name': 'Версия продукта', 'verbose_name_plural': 'Версии продукта'},
        ),
    ]
