# Generated by Django 4.2.7 on 2024-11-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data_changed',
            field=models.DateField(auto_now=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='data_created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
