# Generated by Django 4.2.7 on 2024-11-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status_alter_order_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Создан'), (2, 'В сборке'), (3, 'В доставке'), (4, 'Завершен'), (0, 'Отменен')], default=1, verbose_name='Статус'),
        ),
    ]
